// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ken1kasap/learning-wire/msg"
)

// Injectors from wire.go:

func InitializeEvent() msg.Event {
	message := msg.NewMessage()
	greeter := msg.NewGreeter(message)
	event := msg.NewEvent(greeter)
	return event
}
